branches:
  only:
    - master
    - feat/offline-only-index
osx_image: xcode8
language: objective-c
env:
  matrix:
    - PLATFORM="OSX"    SDK="macosx10.12"                                                             FASTLANE_TARGET="ios"
    - PLATFORM="iOS"    SDK="iphonesimulator10.0"    DESTINATION="OS=10.0,name=iPhone 6"              FASTLANE_TARGET="mac"
    - PLATFORM="tvOS"   SDK="appletvsimulator10.0"   DESTINATION="OS=10.0,name=Apple TV 1080p"        FASTLANE_TARGET="tv"
install: true
before_script:
  - gem install xcpretty -N
script:
  - set -o pipefail
  - fastlane ${FASTLANE_TARGET} test
